"""
src/tools/schema_rag.py — Metadata RAG for the Schema & Lineage Agent
--------------------------------------------------------------------------
Parses the REAL dbt manifest.json (generated by `dbt run`/`dbt compile`)
and embeds it into ChromaDB. This is what lets the Schema & Lineage Agent
answer questions like "what does this table mean?" and "what depends on
this table?" by semantic search over real documentation, not guessing.

One document per model, one document per source table. Each document's
text includes the description, columns (with their own descriptions),
and — for models — real lineage (which sources it depends on, computed
by dbt itself from the source() references in the SQL).

Run standalone to (re)ingest:
    python src/tools/schema_rag.py ingest

Run standalone to test a search:
    python src/tools/schema_rag.py search "why would total_revenue break"
"""

import json
import chromadb

MANIFEST_PATH = "dbt_project/target/manifest.json"
DB_PATH = "data/chroma_schema_db"
COLLECTION_NAME = "schema_metadata"


def _get_collection():
    client = chromadb.PersistentClient(path=DB_PATH)
    return client.get_or_create_collection(name=COLLECTION_NAME)


def _build_model_document(model: dict) -> tuple[str, dict]:
    """Turns one dbt model node into a searchable text document + metadata."""
    name = model["name"]
    description = model.get("description") or "(no description)"

    columns_text = []
    for col_name, col_info in model.get("columns", {}).items():
        col_desc = col_info.get("description") or "(no description)"
        columns_text.append(f"  - {col_name}: {col_desc}")

    depends_on = model.get("depends_on", {}).get("nodes", [])
    depends_on_names = [d.split(".")[-1] for d in depends_on]

    doc_text = f"""MODEL: {name}
DESCRIPTION: {description}
COLUMNS:
{chr(10).join(columns_text) if columns_text else "  (none documented)"}
DEPENDS ON (upstream sources/models): {", ".join(depends_on_names) if depends_on_names else "(none)"}
"""

    metadata = {
        "doc_type": "model",
        "name": name,
        "unique_id": model["unique_id"],
        "depends_on": ",".join(depends_on_names),
    }
    return doc_text, metadata


def _build_source_document(source: dict) -> tuple[str, dict]:
    """Turns one dbt source node into a searchable text document + metadata."""
    name = source["name"]
    source_name = source["source_name"]
    description = source.get("description") or "(no description)"

    columns_text = []
    for col_name, col_info in source.get("columns", {}).items():
        col_desc = col_info.get("description") or "(no description)"
        columns_text.append(f"  - {col_name}: {col_desc}")

    doc_text = f"""SOURCE TABLE: {source_name}.{name}
DESCRIPTION: {description}
COLUMNS:
{chr(10).join(columns_text) if columns_text else "  (none documented)"}
"""

    metadata = {
        "doc_type": "source",
        "name": name,
        "unique_id": source["unique_id"],
        "depends_on": "",
    }
    return doc_text, metadata


def ingest_manifest(manifest_path: str = MANIFEST_PATH) -> dict:
    """
    Reads the real dbt manifest.json and embeds every model + source into
    ChromaDB. Safe to re-run — replaces the collection each time so it
    always reflects the current state of the dbt project.
    """
    with open(manifest_path) as f:
        manifest = json.load(f)

    client = chromadb.PersistentClient(path=DB_PATH)
    # Drop and recreate so stale docs from renamed/removed models don't linger
    try:
        client.delete_collection(COLLECTION_NAME)
    except Exception:
        pass
    collection = client.get_or_create_collection(name=COLLECTION_NAME)

    documents, metadatas, ids = [], [], []

    # Models
    for unique_id, node in manifest.get("nodes", {}).items():
        if node.get("resource_type") == "model":
            doc_text, metadata = _build_model_document(node)
            documents.append(doc_text)
            metadatas.append(metadata)
            ids.append(unique_id)

    # Sources
    for unique_id, source in manifest.get("sources", {}).items():
        doc_text, metadata = _build_source_document(source)
        documents.append(doc_text)
        metadatas.append(metadata)
        ids.append(unique_id)

    if documents:
        collection.add(documents=documents, metadatas=metadatas, ids=ids)

    return {"models_ingested": sum(1 for m in metadatas if m["doc_type"] == "model"),
            "sources_ingested": sum(1 for m in metadatas if m["doc_type"] == "source")}


def search_schema_context(query: str, n_results: int = 3) -> list[dict]:
    """
    Semantic search over the ingested schema metadata. This is what the
    Schema & Lineage Agent calls to answer "what does this mean / what
    depends on this" given a query derived from a real pipeline failure.
    """
    collection = _get_collection()
    if collection.count() == 0:
        return []

    n_results = min(n_results, collection.count())
    results = collection.query(query_texts=[query], n_results=n_results)

    matches = []
    for i in range(len(results["ids"][0])):
        matches.append({
            "id": results["ids"][0][i],
            "text": results["documents"][0][i],
            "name": results["metadatas"][0][i]["name"],
            "doc_type": results["metadatas"][0][i]["doc_type"],
            "depends_on": results["metadatas"][0][i]["depends_on"],
            "distance": results["distances"][0][i],
        })
    return matches


if __name__ == "__main__":
    import sys

    if len(sys.argv) > 1 and sys.argv[1] == "search":
        query = " ".join(sys.argv[2:]) or "order_amount type error"
        print(f"Searching for: {query}\n")
        results = search_schema_context(query)
        for r in results:
            print(f"[{r['doc_type']}] {r['name']} (distance={r['distance']:.3f})")
            print(r["text"])
            print("-" * 60)
    else:
        stats = ingest_manifest()
        print(f"Ingested {stats['models_ingested']} model(s) and {stats['sources_ingested']} source(s).")

        print("\n--- Test search: 'order_amount type error' ---\n")
        results = search_schema_context("order_amount type error")
        for r in results:
            print(f"[{r['doc_type']}] {r['name']} (distance={r['distance']:.3f})")
            print(r["text"])
            print("-" * 60)